config/routes.rb
Rails.application.routes.draw do

  root to: "static_pages#app" # A must for devise.

  get 'app' => "static_pages#app"
  get 'home' => "static_pages#home"

  devise_for :users, controllers: { registrations: 'users/registrations', passwords: 'users/passwords' }

  resources :users, only: [:show]

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :username
    devise_parameter_sanitizer.for(:account_update) << :username
  end
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def app
    redirect_to :home unless current_user
  end

  def home; end

  def about; end

end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  protected
    def after_resetting_password_path_for(resource)
      # signed_in_root_path(resource)
    end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

  protected
  # def after_sign_up_path_for(resource)
  # end
  #
  # def after_update_path_for(resource)
  #   # signed_in_root_path(resource)
  # end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to :back, :alert => "Access denied."
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <svg id="logo"></svg>
    </div>
    <div class="collapse navbar-collapse" id="auth-headers">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to current_user.username, user_url(current_user) %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "wrkstrm" %></title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/navigation' %>

  <div class="container" id="content">
    <%= render 'layouts/messages' %>
    <%= yield %>
  </div>
</body>

<script type="application/javascript">
  $(document).ready( function () {
    var logo = new RismayLogo.Logo("#logo");

    d3.select(window).on("resize", function () {
      logo.scale();
    });
  });
</script>

</html>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/app.html.erb
<div id="app_content"></div>

app/views/static_pages/home.html.erb
<div class="row text-center">
  <div class="col-xs-offset-1 col-xs-10">
    <svg id="logo"> </svg>
    <hr/>
    <h2 id="wrkstrm_header"><b>Rismay</b> <i>noun</i> </h2>
    <h3 id="wrkstrm_definition_header">
      A workstream is a set of associated <i>activities</i> <br> focused around a particular <i>aspect</i> of life.
    </h3>
  </div>
  <div class="col-xs-offset-3 col-xs-6">
    <svg id="force"> </svg>
    <hr/>
  </div>

  <div class="col-xs-offset-3 col-xs-6">
    <h2 id="word_header"> <b> Agendas</b> </h2>
    <h3 id="definition_header"> wrkstrm keeps track of what you do by categorizing your life into <i>five aspects </i> via agendas.</h3>
      <%= button_to 'Try it', new_user_registration_url, class: "btn btn-primary btn-lg", method: :get%>
      <hr/>
  </div>
</div>

<script type="application/javascript">
  $(document).ready( function () {
    var logo = new RismayLogo.Logo("#logo");

    d3.select(window).on("resize", function () {
      logo.scale();
    });
  });
</script>